<a href="https://colab.research.google.com/github/sohanchelekar276/WiDS-Midterm-Report/blob/main/WiDS_Assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Q1 Part 1: Initialization and Tasks (a), (b), (c)
This block handles the creation of the array and the basic statistical operations.

In [ ]:
import numpy as np

#We use 101 as the upper bound as randint doesnt take the highest value
arr = np.random.randint(1, 101, size=(5,5))

print("Original array")
print(arr)
print("-"*30)

# (a) Extract and print the middle element
# Since the shape is (5, 5), the indices are 0, 1, 2, 3, 4.
# The exact middle is at row index 2 and column index 2.

middle_element = arr[2,2]
print(f"(a) Middle element: {middle_element}")

# (b) Calculate mean of each row
# axis=1 means we calculate 'across' the columns (horizontally) for each row

row_means = np.mean(arr, axis=1)
print(f"(b) Row means: {row_means}")

#(c) Filter elements greater than the overall mean

overall_mean = np.mean(arr)
greater_than_mean = arr[arr> overall_mean]

print(f"(c) Overall Mean: {overall_mean:.2f}")
print(f"    Elements greater than overall mean: {greater_than_mean}")




Original array
[[21 67 12 65 88]
 [97 87 40 91 76]
 [78 31 18 88  1]
 [76 42 75 90 95]
 [ 6 50 30 83 46]]
------------------------------
(a) Middle element: 18
(b) Row means: [50.6 78.2 43.2 75.6 43. ]
(c) Overall Mean: 58.12
    Elements greater than overall mean: [67 65 88 97 87 91 76 78 88 76 75 90 95 83]


Q1 Part 2: The Spiral Order Function (d)
This is the logic to traverse the matrix in a spiral. We use four pointers (top, bottom, left, right) to define the boundaries of the box we haven't visited yet, shrinking them as we loop.

In [ ]:
# (d) Function for Spiral Order
def numpy_spiral_order(matrix):
    result = []

    # Define our boundaries
    top = 0
    bottom = matrix.shape[0] - 1
    left = 0
    right = matrix.shape[1] - 1

    while top <= bottom and left <= right:
        # 1. Traverse from Left to Right (along the Top row)

        for i in range(left, right + 1):
            result.append(matrix[top, i])
        top += 1  # Move the top boundary down

        # 2. Traverse from Top to Bottom (along the Right column)

        for i in range(top, bottom + 1):
            result.append(matrix[i, right])
        right -= 1 # Move the right boundary left

        # Check if we still have valid rows/cols remaining
        if top <= bottom:
            # 3. Traverse from Right to Left (along the Bottom row)

            for i in range(right, left - 1, -1):
                result.append(matrix[bottom, i])
            bottom -= 1 # Move the bottom boundary up

        if left <= right:
            # 4. Traverse from Bottom to Up (along the Left column)


            for i in range(bottom, top - 1, -1):
                result.append(matrix[i, left])
            left += 1 # Move the left boundary right

    return result

# Testing the function

print("-" * 30)
spiral_result = numpy_spiral_order(arr)
print("(d) Spiral order:", spiral_result)

------------------------------
(d) Spiral order: [np.int64(21), np.int64(67), np.int64(12), np.int64(65), np.int64(88), np.int64(76), np.int64(1), np.int64(95), np.int64(46), np.int64(83), np.int64(30), np.int64(50), np.int64(6), np.int64(76), np.int64(78), np.int64(97), np.int64(87), np.int64(40), np.int64(91), np.int64(88), np.int64(90), np.int64(75), np.int64(42), np.int64(31), np.int64(18)]


Q2

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv('videogamesales.csv')

# Task (a): Add 'global sales', sort, and print
# Calculate total sales by summing all regions
df['Global_Sales_Calculated'] = df['NA_Sales'] + df['EU_Sales'] + df['JP_Sales'] + df['Other_Sales']

# Sort the DataFrame by the new column in descending order (highest first)
df_sorted = df.sort_values(by='Global_Sales_Calculated', ascending=False)

print("(a) Top 5 games by Global Sales:")
print(df_sorted[['Name', 'Global_Sales_Calculated']].head())
print("-" * 30)

#  Task (b): Plot total copies sold of each genre globally
# Group by Genre and sum the calculated global sales
genre_sales = df.groupby('Genre')['Global_Sales_Calculated'].sum().sort_values(ascending=False)

plt.figure(figsize=(10, 6))
genre_sales.plot(kind='bar', color='skyblue')
plt.title('Total Global Sales by Genre')
plt.xlabel('Genre')
plt.ylabel('Global Sales (Millions)')
plt.xticks(rotation=45)
plt.show()

# Task (c): Filter 'Grand Theft Auto' games and show details
# Filter rows where the Name contains "Grand Theft Auto"
gta_games = df[df['Name'].str.contains('Grand Theft Auto', case=False)].copy()

# Calculate sum of Europe and Japan sales for these games
gta_games['EU_JP_Sales'] = gta_games['EU_Sales'] + gta_games['JP_Sales']

# Select only the required columns: Name, Platform, Year, EU+JP Sales
gta_display = gta_games[['Name', 'Platform', 'Year', 'EU_JP_Sales']]

print("\n(c) Grand Theft Auto Games (Name, Platform, Year, EU+JP Sales):")
print(gta_display)
print("-" * 30)

# --- Task (d): Pie chart of total sales for ALL GTA games combined ---
# Sum up the sales for each region across all GTA games found
total_na = gta_games['NA_Sales'].sum()
total_eu = gta_games['EU_Sales'].sum()
total_jp = gta_games['JP_Sales'].sum()
total_other = gta_games['Other_Sales'].sum()

# Prepare data for the pie chart
sales_data = [total_na, total_eu, total_jp, total_other]
labels = ['North America', 'Europe', 'Japan', 'Other']
colors = ['#ff9999','#66b3ff','#99ff99','#ffcc99']

plt.figure(figsize=(7, 7))
plt.pie(sales_data, labels=labels, autopct='%1.1f%%', startangle=140, colors=colors)
plt.title('Distribution of Sales for All Grand Theft Auto Games')
plt.show()

FileNotFoundError: [Errno 2] No such file or directory: 'videogamesales.csv'